### PR TITLE
Removal of unnecessary text from README

### PR DESCRIPTION
**Pull request by kwoot**
Subject says it all.

### CODE REVIEW

**Comment by tobyhinloopen** [comment]
This is a great and important contribution to one of the greatest national open source projects.

**Comment by githrdw** [comment]
Totally agree. I am surprised that a government agency dares to put a widely supported platform like Linux in a negative light.
It can also be an inside joke, of course, but it does seem quite childish, especially for large public projects like this. As a government agency, you should set a good example, and that should not include breaking down operating systems in this way.
I imagine the team doesn't have a lot of experience with Linux, but to communicate this way is going too far.

Each platform has its qualities and it is almost impossible to compare them. However, to return to the question of who uses it, this source says enough
 https://w3techs.com/technologies/overview/operating_system
(for the team: Linux is a UNIX-like one)

**Comment by ijansch** [comment]
I already removed it in https://github.com/minvws/nl-covid19-notification-app-backend/pull/1/files as soon as I saw it.

**Comment by dirkx** [comment]
Odd - I still see it on https://github.com/minvws/nl-covid19-notification-app-backend/blob/master/README.md and https://github.com/minvws/nl-covid19-notification-app-backend.

Did it get put back in ?

Dw.

**Comment by ijansch** [comment]
No the pull wasn’t merged yet. That’s why you still see it. I’ll close this one as a duplicate.

**Comment by kwoot** [comment]
It is unfortunate that this vital fix on such important piece of Dutch national software has not been merged. Now what am I going to tell my grand kids later when they ask me what I did during the pandemic? :-)

**Pull request closed without merging**
